apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: open-cache
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            - name: S3_REGION
              value: {{ .Values.s3.region | quote }}
            - name: LISTEN_ADDR
              value: ":{{ .Values.server.port }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "2"
              memory: 1Gi
